Korteg = ("Zheka","Bohdan","Vova","Sasha","Vova")
print(Korteg)
for i in Korteg:
    print(i)
print(Korteg.index("Vova"))
print(Korteg.count("Vova"))
KortegInt = (100,54,45,60,500,39)
print(max(KortegInt))
print(min(KortegInt))
print(sum(KortegInt))